### ISSUE TITLE
Разделения кода сервера и клиента

### ISSUE THREAD

**Issue by xDiaym** [romka-best/NeoBrain_App#2]
Код сервера и клиента находится в одном репозитории, что не является лучшей практикой.

Проблемы, которые приносит такой подход:
- Такой подход запутывает
- Неудобство при pull request
- Усложние структуры при добавлении новых компонентов

В качестве решения предлагаю создать отедльные репозитории для клента и сервера.

**Comment by romka-best** [comment]
Здравствуйте, <a href="https://github.com/xDiaym"> Xdiaym</a>!

Да, мы тоже об этом думали. Считаю, что в ближайшее время мы поделим клиент и сервер на разные репозитории. Спасибо, что сообщили нам об этом!

С уважением,
команда NeoTeam
